In [1]:
import numpy as np
from PIL import Image

# Foo

In [2]:
arr_1d = np.array([1,2,3,4,5])

arr_1d

array([1, 2, 3, 4, 5])

In [5]:
arr_2d = np.array([
    [1,2,3],
    [5,6,9],
    [66, 42, 666]
    ])

print(arr_2d)

arr_3d = np.array([
    [[1,0], [0,0]],
    [[0,0], [0,1]],
    [[1,1], [1,1]]
    ])

print(arr_3d)

[[  1   2   3]
 [  5   6   9]
 [ 66  42 666]]
[[[1 0]
  [0 0]]

 [[0 0]
  [0 1]]

 [[1 1]
  [1 1]]]


In [7]:
print([1, 2, 44, 66])

[1, 2, 44, 66]
