<br><br><center><h1 style="font-size:2em;color:#2467C0">Tagesaufgaben</h1></center>
<br>


# Numpy

## Aufgabe 1

<div  class="alert alert-block alert-info">
1. Erstelle ein eindimensionales array und wandel es anschließend in ein zweidimensionales array der folgenden Form um:

    Output:
    [[12 23]
     [31 25]
     [65 98]]
</div>

In [1]:
import numpy as np
# "Von Hand"
oned = np.array([12, 23, 31, 25, 65, 98])
threed = np.array([oned[0:2], oned[2:4], oned[4:6]])
print(threed)
# oder so:
print(oned.reshape(3, 2))
# print(len(threed))
    

[[12 23]
 [31 25]
 [65 98]]
[[12 23]
 [31 25]
 [65 98]]


<div  class="alert alert-block alert-info">
2. Gegeben sind folgende Arrays. Schreibe eine Funktion die überprüft, ob ein array eindimensional oder zweidimensional ist. Wenn das array eindimensional ist, soll es in ein zweidimensionales der Form 2,2 umgewandelt werden. Wenn es zweidimensional ist, soll es in ein eindimensionales umgewandelt werden. Optional: Teste weitere Arrays an deiner Funktion und füge eine try&except Bedingung mit ein, um eventuelle error abzufangen.

    Output:
    [[20 23]
     [12 34]]
     [23 34 12 45]

</div>

In [46]:
def redim_array(foo):
    dim = np.ndim(foo)
    if dim ==1:
        arr = foo.reshape(2,2)
    elif dim ==2:
        arr = foo.flatten()
    else:
        
        arr = None
    
    return arr

array1 = np.array([20,23,12,34])
array2 = np.array([[23,34],[12,45]])
ra1 = redim_array(array1)
ra2 = redim_array(array2)
print(ra1)
print(ra2)
# Just testing ...
array3 = np.array([[[1, 12, 33], [23, 34, 66], [45, 56, 99]]])
assert(redim_array(array3) == None)



[[20 23]
 [12 34]]
[23 34 12 45]


<div  class="alert alert-block alert-info">
3. Gegeben ist folgendes Array. Sortiere die Zahlen im Array.

    Output:
    [12 20 23 34]
</div>

In [2]:
array1 = np.array([20,23,12,34])
array1.sort()
print(array1)

[12 20 23 34]


<div  class="alert alert-block alert-info">
4. Erstelle zwei arrays. Füge beide arrays zusammen. Nutze dafür zwei verschiedene Befehle.

    Output:
    [20 23 12 34 23 34 12 45]
    [20 23 12 34 23 34 12 45]
</div>

In [ ]:
li1 = [20, 23, 12, 34]
li2 = [23, 34, 12, 45]
arr1 = np.array(li1)
arr2 = np.array(li2)

# Variante A
arr_neu1 = np.array(li1+li2)

# Variante B
arr_neu2 = np.concatenate((arr1, arr2))

print(arr_neu1)
print(arr_neu2)

[20 23 12 34 23 34 12 45]
[20 23 12 34 23 34 12 45]


<div  class="alert alert-block alert-info">
5. Erstelle ein eindimensionales array und teile es in zwei arrays auf. Optional: Speichere das Ergebnis der Teilung in zwei Variablen. Nutze dafür nur eine Zeile Code.

    Output:
    [array([20, 23]), array([12, 34])]
</div>

In [47]:
arr1, arr2 = np.split(np.array([20, 23, 12, 34]), 2)
print(arr1, arr2)

[20 23] [12 34]


<div  class="alert alert-block alert-info">
6. Gegeben ist folgendes array. Lass dir die Index Position ausgeben, an der sich der Name Sara befindet.

    Output:
    (array([1], dtype=int64),)
</div>

In [49]:
array3 = np.array(["Alex", "Sara", "Annika", "Max", "Julian"])
result = np.where(array3 == 'Sara')
print(result[0])
print(result)

[1]
(array([1]),)


<div  class="alert alert-block alert-info">
7. Gegeben ist folgendes array. Durchsuche wieder das array nach dem Namen Sara aber lass dir dieses Mal eine Liste mit Booleschen Werten für jeden Index des array ausgeben.

    Output:
    [False  True False False False]
</div>

In [50]:
array3 = np.array(["Alex", "Sara", "Annika", "Max", "Julian"])

r = [True if x == 'Sara' else False for x in array3]
print(r)

# Oder:

result = np.where(array3 == 'Sara', True, False)
print(result)

[False, True, False, False, False]
[False  True False False False]


<div  class="alert alert-block alert-info">
8. Gegeben ist folgendes array. Überprüfe ob in dem array der Name Hans vorkommt.

    Output:
    False
</div>

In [35]:
array3 = np.array(["Alex", "Sara", "Annika", "Max", "Julian"])
print('Hans' in array3)
assert('Annika' in array3)

False


<div  class="alert alert-block alert-info">
9. Erstelle ein eindimensionales array mit 8 Zahlen. Lass dir den maximalen Wert und die Summe der Zahlen im array ausgeben.

    Output:
    67
    206
</div>

In [11]:
foo = np.array([22, 456, 77, 12, 33, 44, 32, 11])
print(np.amin(foo))
print(np.amax(foo))

11
456


<div  class="alert alert-block alert-info">
10. Lass dir den Mittelwert des arrays aus Aufgabe 9 ausgeben.

    Output:
    25.75
</div>

In [32]:
print(np.mean(foo))
assert(np.mean(foo) == sum(foo)/len(foo))

85.875


# Optional

Fasse die Lerninhalte von heute nochmal zusammen und notiere dir Fragen, die dir dabei kommen!